AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 132

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 25

Metrics/MethodLength:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10
