AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - Brewfile

Style/HashLikeCase:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringConcatenation:
  Enabled: false

Layout/LineLength:
  Max: 132

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 25

Metrics/MethodLength:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10
