require 'json'
require 'logger'
require 'parslet'
require 'wrapsher'
require 'pry'

module Wrapsher
  class Generator
    def initialize(logger: nil, level: nil)
      @logger = logger || Logger.new($stderr)
      @logger.level = level || :DEBUG
    end

    def generate(program, filename: '-')
      case program
      when Array
        nodes = program.map { |obj| Wrapsher::Node.from_obj(obj, filename: filename) }
      when Hash
        nodes = [Wrapsher::Node.from_obj(program, filename: filename)]
      end
      <<~EOF
      #!/bin/sh
      # Generated by Wrapsher
      # #{program.to_s}
      : <<EOT
      #{nodes.inspect}
      EOT
      #{preamble}
      #{nodes.map(&:to_s).join("\n")}
      #{postamble}
      EOF
    end

    def preamble
      <<~EOF
      __wsh_result='null:'
      __wsh_error='null:'
      EOF
    end

    # Need to get the node tree back and figure out stuff like
    # if it's a module, but actually for now we assume it's a
    # program.
    def postamble
      <<~EOF
      # startup code
      # construct array from raw string array $@
      __wsh_int_main
      exit "${__wsh_result#int:}"
      EOF
    end
  end
end
