# frozen_string_literal: true

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2025 Mermaidpurse

require 'json'
require 'logger'
require 'parslet'
require 'wrapsher'
require 'pry'

module Wrapsher
  # Generates wsh code based on passed-in program object
  class Generator
    def initialize(logger: nil, level: nil, type: :program)
      @logger = logger || Logger.new($stderr)
      @logger.level = level || :DEBUG
      @type = type
    end

    def preamble
      if @type == :program
        File.read(File.join(__dir__, 'preamble.sh'))
      else
        ''
      end
    end

    def find_test_functions(nodes)
      nodes.select do |node|
        node.is_a?(Wrapsher::Node::FunStatement) && node.signature.name.start_with?('test_')
      end
    end

    def wsh_preamble
      if @type == :program
        [Wrapsher::Parser.new.parsetext(File.read(File.join(__dir__, 'preamble.wsh')))].flatten
      else
        []
      end
    end

    def postamble
      if @type == :program
        File.read(File.join(__dir__, 'postamble.sh'))
      else
        ''
      end
    end

    def docs(program, tables: nil)
      nodes = [program].flatten.map do |obj|
        Wrapsher::Node.from_obj(obj, tables: tables)
      end
      meta_nodes = nodes.select do |node|
        node.is_a? Wrapsher::Node::Meta
      end
      doc = []
      meta_nodes.each do |node|
        doc += [node.doc] if node.doc
      end
      doc.join("\n").delete_prefix("\n")
    end

    def generate(program, tables: nil)
      nodes = (wsh_preamble + [program].flatten).map do |obj|
        Wrapsher::Node.from_obj(obj, tables: tables)
      end

      nodes = tables.to_nodes + nodes if @type == :program
      errors = nodes.map(&:errors).flatten.compact
      if errors.any?
        @logger.error 'Compilation errors:'
        errors.each do |error|
          @logger.error "  - #{error}"
        end
        raise Wrapsher::CompilationError, "Compilation failed with #{errors.size} errors"
      end

      lines = []
      lines << (tables.options[:profile] ? profile_shebang(tables.options[:profile]) : shebang)
      lines << showtables(tables) if @type == :program
      lines << preamble
      lines << '_wsh_prof_init' if tables.options[:profile]
      lines << nodes.map(&:to_s).join("\n")
      lines << postamble
      lines.join("\n")
    end

    def profile_shebang(bash)
      if @type == :program
        <<~SHEBANG
          #!#{bash} --posix
          # Generated by Wrapsher for profiling
        SHEBANG
      else
        '# included'
      end
    end

    def shebang
      if @type == :program
        <<~SHEBANG
          #!/bin/sh
          # Generated by Wrapsher
        SHEBANG
      else
        '# included'
      end
    end

    def showtables(tables)
      <<~TABLES
        : <<EOT
        #{tables}
        EOT
      TABLES
    end
  end
end
