require 'json'
require 'logger'
require 'parslet'
require 'wrapsher'
require 'pry'

module Wrapsher
  class Generator
    def initialize(logger: nil, level: nil, type: :program)
      @logger = logger || Logger.new($stderr)
      @logger.level = level || :DEBUG
      @type = type
    end

    def preamble
      if @type == :program
        File.read(File.join(__dir__, 'preamble.sh'))
      else
        ''
      end
    end

    def wsh_preamble
      if @type == :program
        [Wrapsher::Parser.new.parsetext(File.read(File.join(__dir__, 'preamble.wsh')))].flatten
      else
        []
      end
    end

    def postamble
      if @type == :program
        File.read(File.join(__dir__, 'postamble.sh'))
      else
        ''
      end
    end

    def generate(program, filename: '-')
      nodes = (wsh_preamble + [program].flatten).map do |obj|
        Wrapsher::Node.from_obj(obj, filename: filename)
      end

      [
        shebang,
        showtree(nodes),
        preamble,
        nodes.map(&:to_s).join("\n"),
        postamble
      ].join("\n")
    end

    def shebang
      if @type == :program
        <<~EOF
        #!/bin/sh
        # Generated by Wrapsher
        # {program.to_s}
        EOF
      else
        '# included'
      end
    end

    def showtree(nodes)
      <<~EOF
      : <<'EOT'
      #{nodes.inspect}
      EOT
      EOF
    end
  end
end
